### ISSUE TITLE
Custom muzzle/suppresors attachments don't align correctly with effects

### ISSUE THREAD

**Issue by CurlySparkle** [HaodongMo/ARC-9#104]
Bit confusing on the title but to explain about it, when using custom muzzles or suppressors, the muzzle flash of the QCA that the attachment has won't align correctly specially sometimes it plays inside the weapon or way too close, as far as this been tested, you have to move the muzzle/suppressor QCA way too far to get some decent results which is annoying.

![1](https://user-images.githubusercontent.com/5094277/203405272-ff10210a-3955-4b08-b3f1-39817a9069d6.png)
![2](https://user-images.githubusercontent.com/5094277/203405277-d33d9dda-65aa-4303-b5b9-7673094aa5da.png)

**Comment by HaodongMo** [comment]
Issue with your muzzle effects. Cannot recreate on any guns apart from CSGO ones
