### ISSUE TITLE
physbullet/penetration will still display errors

### ISSUE THREAD

**Issue by CurlySparkle** [HaodongMo/ARC-9#105]
Following after the fix related with physbullets/penetration when bullets going out of bounds, seems that there are still a remaining error that needs to be checked out, this is just a reminder.

![Screenshot_2022-11-25_](https://user-images.githubusercontent.com/5094277/204068695-1f1f05b4-1e0b-4f99-9a71-d4f8edae5e02.png)

**Comment by dar-su** [comment]
I dont think it matter too much since this error appears on every addon with guns

**Comment by CurlySparkle** [comment]
it still quite a concern since it might be fixable but something look out for, can spam alot if use weapons with a high rpm.

**Comment by HaodongMo** [comment]
Not related to ARC9, also not an actual problem
