### ISSUE TITLE
Gmod crash related to penetration pls fix

### ISSUE THREAD

**Issue by dar-su** [HaodongMo/ARC-9#122]
Executable: C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\bin\win64\gmod.exe

-Lua Stack Traces-
==================
  Client
    *Not in Lua call OR Lua has panicked*

  Server
    0. TraceLine - [C]:-1
      1. Penetrate - addons/arc-9/lua/weapons/arc9_base/sh_penetration.lua:144
        2. AfterShotFunction - addons/arc-9/lua/weapons/arc9_base/sh_shoot.lua:633
          3. (null) - addons/arc-9/lua/weapons/arc9_base/sh_penetration.lua:196
            4. FireBullets - [C]:-1
              5. Penetrate - addons/arc-9/lua/weapons/arc9_base/sh_penetration.lua:187
                6. AfterShotFunction - addons/arc-9/lua/weapons/arc9_base/sh_shoot.lua:633
                  7. (null) - addons/arc-9/lua/weapons/arc9_base/sh_penetration.lua:196
                    8. FireBullets - [C]:-1
                      9. Penetrate - addons/arc-9/lua/weapons/arc9_base/sh_penetration.lua:187
                        10. AfterShotFunction - addons/arc-9/lua/weapons/arc9_base/sh_shoot.lua:633
                          11. (null) - addons/arc-9/lua/weapons/arc9_base/sh_penetration.lua:196
                            12. FireBullets - [C]:-1
                              13. Penetrate - addons/arc-9/lua/weapons/arc9_base/sh_penetration.lua:187
                                14. AfterShotFunction - addons/arc-9/lua/weapons/arc9_base/sh_shoot.lua:633
                                  15. (null) - addons/arc-9/lua/weapons/arc9_base/sh_penetration.lua:196
                                    16. FireBullets - [C]:-1

  MenuSystem
    *Not in Lua call OR Lua has panicked*

**Comment by HaodongMo** [comment]
Hopefully should be fixed, I can't reliably repro this so see if it still happens
