### ISSUE TITLE
m24 iron sight is bugged on bipod

### ISSUE THREAD

**Issue by freeaim** [HaodongMo/ARC-9#126]
[https://streamable.com/domr41](url)

**Comment by freeaim** [comment]
![gmod exe Screenshot 2022 12 25 - 14 14 35 51](https://user-images.githubusercontent.com/11797565/209457682-e84c3d46-343d-417c-8a0e-00621e5e9fed.png)

**Comment by HaodongMo** [comment]
Not the right repo

**Comment by freeaim** [comment]
oshit
