### ISSUE TITLE
Suggestions And Ideas

### ISSUE THREAD

**Issue by VolatileIvory** [HaodongMo/ARC-9#13]
As soon as I heard this base existed, I immediately thought of things that would've made ArcCW better that could be added to ARC9. So, here are those ideas in a hopefully not awful format.

Varying reload times/animations. Essentially reloads wouldn't always take exactly X seconds or use the same animation every time, but instead vary slightly between times and animations for more realism. This could also allow for training packages (Urban Coalition style) that decrease reload time variance or even some convoluted system that varies reload time less the more you use a weapon. You could even go all the way with this concept and make ADS time and malfunction clear time vary, but that would probably take way too much time to code.
Flat textured sight reticles. Instead of making the reticle of holographic sights snap to the crosshair, make them flat textures on the sight. This is a bit situational, but it would fix a lot of problems with view bobbing mods and other similar mods that affect the viewmodel.
Armour penetration. I always thought that ArcCW penetration was pretty useless because it didn't pierce suit armour (I only play singleplayer though, so I might be wrong on that). Making it so that better penetration can actually pierce through suit armour or even things like JMod armour would be amazing.
Weapon carry limits. By default, GMod lets you carry the equivalent of an entire US Army surplus worth of guns without any consequences. If you could somehow make a carry limit so you can only have so many weapons at a time, it would make gameplay much more realistic.

Just to be clear, I don't expect you to add any of these, but if you did that would be great.

**Comment by VolatileIvory** [comment]
Also, I just found out that toggle ADS isn't an option, could you please add that soon?

**Comment by HaodongMo** [comment]
Varying reload times won't add much, and it'd be a bit of a pain to implement. It could be done, but not unless I'm shown a compelling use case.

Proficiency is an annoying mechanic for GMod SWEPs. Besides, the mechanic can be implemented using something like ReloadTimeHook anyway, or with attachments.

Flat textured sight reticules will not be happening. If you have mods that do these things, uninstall them.

SWEP.ArmorPiercing.

Install a different mod for carry limits.
