### ISSUE TITLE
Switching weapons on certain guns

### ISSUE THREAD

**Issue by Joyfoxy** [HaodongMo/ARC-9#131]
When I switch out of guns like the MSA-30, Konstruktie 95, p40a3, TDR-90 and go back into them the viewmodel just goes into the worlds start point and gets stuck in the sky and is not in place of my pov which gets annoying. If you somehow fix this issue this addon would be perfect. Thank you!

**Comment by dar-su** [comment]
Skill issue

**Comment by Fesiug** [comment]
what
