### ISSUE TITLE
ARC9 : Some weapons like to drop magazines,

### ISSUE THREAD

**Issue by ickypop** [HaodongMo/ARC-9#132]
it looks very unnatural sometimes, on a sidenote. The modifier system is a little too complicated for smooth-brains like me, thanks.

**Comment by dar-su** [comment]
mag drop position is set uped by gun creator
modifer system IS complicated (we know), we couldn't finish quick ez system to release
![image](https://user-images.githubusercontent.com/95997959/210168747-19d7b811-f01a-4477-b56d-c91b92f8b79c.png)
