### ISSUE TITLE
Main weapon and UB weapon ammo types stack

### ISSUE THREAD

**Issue by StanPiPJacobs** [HaodongMo/ARC-9#147]
UB shotgun gets ammo type from main weapon.
Example: XM1014 with UB shotgun. Birdshot on UB, Explosive on main. UB shoots like birdshot would, but with explosive rounds.

**Comment by dar-su** [comment]
Can't be fixed due to how ubgl system works

Creator of addon needs to include all funny ammo stats into ubgl table but defaulted to weapon stats
Like ATT.RicochetChanceUBGL = 0 ATT.ExplosionDamageUBGL = false etc
