### ISSUE TITLE
Weird animation when switching weapons

### ISSUE THREAD

**Issue by DELNEMESIS** [HaodongMo/ARC-9#167]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/105528735/212537630-39a60dd0-bf05-4b7f-8ad3-669042e46527.gif)
There is a problem that when I switch weapons, the animation plays like the GIF above and then switches.
I'm submitting this issue because this could be a bug caused by another addon overlapping with that addon, or a bug that hasn't been fixed.

**Comment by DELNEMESIS** [comment]
Recently known weapons are FA:S 2's full arsenal and GSR's Famas and Benelli M3 Super.

**Comment by littlebabyman** [comment]
you have "weapon switch animation" installed
https://steamcommunity.com/sharedfiles/filedetails/?id=2603130892
it does not give consideration to arc9

**Comment by DELNEMESIS** [comment]
ok. I will remove that addon and reply again

**Comment by DELNEMESIS** [comment]
It works fine. The Weapon Switching Animation addon was the problem. Thank you very much!
