### ISSUE TITLE
Settings panel may cause entire game view to freeze

### ISSUE THREAD

**Issue by TheOnly8Z** [HaodongMo/ARC-9#168]
Need to replicate

https://medal.tv/games/garrys-mod/clips/R7rbr-ezOOkhY/d1337HkMLuAw?invite=cr-MSxWY2YsNzc0NzQzMDIs

**Comment by dar-su** [comment]
#138 ?

**Comment by TheOnly8Z** [comment]
> #138 ?

Looks like it but this one actually has video footage.

**Comment by dar-su** [comment]
https://user-images.githubusercontent.com/95997959/213131549-4ebea161-547e-407a-ab6b-e0fa420ee1b5.mp4
