### ISSUE TITLE
Foldered attachments disappear when free atts. is disabled

### ISSUE THREAD

**Issue by Stalol77** [HaodongMo/ARC-9#172]
Any folder (and thus the contained attachments) will disappear once free attachments is disabled. EXAMPLE: many optics have been using folders to be more orderful between scopes, holosights and whatnot. Disabling free attachments will effectively hide all optic attachments.
![image](https://user-images.githubusercontent.com/95977677/215362140-63d03b41-49e0-401a-b857-22d6105ea2c0.png)
![image](https://user-images.githubusercontent.com/95977677/215362153-8934bf5d-0ff9-4564-a6fa-c28a1a33865f.png)

**Comment by TheOnly8Z** [comment]
Fixed in a3f546e0f6a5ae1d2119b27fa817e6f42aee33d9.
