### ISSUE TITLE
All ARC9 weapons make game unplayable

### ISSUE THREAD

**Issue by buckash105** [HaodongMo/ARC-9#174]
Whenever ANY Arc9 weapon is equipped, game sound is completely gone and my screen flashes in a sickening way. Equipping any other weapon base fixes this.

I am not running any hud mods or anything that should affect the guns showing up (I had VManip and some combat stim addons, but even uninstalling those didn't fix the problem). I've verified files as well.

(EXTREME EPILEPSY WARNING)
https://user-images.githubusercontent.com/122404048/217098214-a01c9485-6593-464d-b9b0-9952cd2be61e.mp4

**Comment by HaodongMo** [comment]
This is a mod conflict. Don't just disable mods you think may be causing the issue, disable ALL mods. Once you figure it out, let us know so we can add it to the incompatibility list and develop a fix.
