### ISSUE TITLE
map transitions not work

### ISSUE THREAD

**Issue by dar-su** [HaodongMo/ARC-9#179]
try stripping/saving gun on GM:ShutDown and giving back new one (with restored ammo and presets) on map initialize

[ARC9 Weapon Base] lua/arc9/shared/sh_move.lua:170: bad argument #2 to '__mul' (number expected, got table)
1. __mul - [C]:-1
2. v - lua/arc9/shared/sh_move.lua:170
3. unknown - lua/includes/modules/hook.lua:96
[ARC9 Weapon Base] lua/arc9/shared/sh_move.lua:24: attempt to perform arithmetic on local 'mult' (a string value)
1. v - lua/arc9/shared/sh_move.lua:24
2. unknown - lua/includes/modules/hook.lua:96
[ARC9 Weapon Base] lua/weapons/arc9_base/sh_util.lua:9: bad argument #1 to 'DoAnimationEvent' (number expected, got string)
1. DoAnimationEvent - [C]:-1
2. DoPlayerAnimationEvent - lua/weapons/arc9_base/sh_util.lua:9
3. unknown - lua/weapons/arc9_base/sh_deploy.lua:64
[ARC9 Weapon Base] lua/includes/extensions/math.lua:166: bad argument #2 to '__add' (Angle expected, got number)
1. __add - [C]:-1
2. Round - lua/includes/extensions/math.lua:166
3. GetCapacity - lua/weapons/arc9_base/sh_reload.lua:275
4. swepIdle - lua/weapons/arc9_base/sh_anim.lua:262
5. unknown - lua/weapons/arc9_base/sh_think.lua:63

Seems that there are some errors after map transition/map loading.

**Comment by Fesiug** [comment]
paste as code noob

**Comment by dar-su** [comment]
Nop

**Comment by dar-su** [comment]
Fixed????????????
