### ISSUE TITLE
Add Impulse Gamemode Support

### ISSUE THREAD

**Issue by Askastaa** [HaodongMo/ARC-9#185]
Hello, im using your ARC9 Weapon base in my server, for my server i use impulse framework and there is a inventory system. When i throw arc9 grenade, the grenade in my inventory still stays.

Ive looked in your code and ive found at [ARC-9] - [lua] - [weapons] - [arc9_base] - sh_grenade.lua
on code line 34 the function Remove(). Which is correct.

I wanted to ask if you can consider replacing self:Remove() with this
```
if self.PairedItem then
	if self:GetOwner():HasInventoryItemSpecific(self.PairedItem) then
		self:GetOwner():TakeInventoryItem(self.PairedItem)
	end
else
	self:Remove()
end
```

**Comment by Fesiug** [comment]
You can open a pull request to do it

**Comment by Askastaa** [comment]
yea i didnt know how to i created one but i cant find it anymore

**Comment by dar-su** [comment]
Make a fork and use it

This thing you pr'ed won't work in any other gamemodes except yours

**Comment by Askastaa** [comment]
May i then upload it to the workshop hidden/edited version? and then update
it with my forked version ?

Am Mo., 13. März 2023 um 06:23 Uhr schrieb Darsu ***@***.***>:

**Comment by dar-su** [comment]
You don't need to upload lua to workshop for server use
You can just use your fork as legacy addon (simply a folder)

**Comment by Askastaa** [comment]
ah so my edited version will override the files i edited but the rest stay
the same ?, alright thanks i will then do it that way

Am Mo., 13. März 2023 um 11:09 Uhr schrieb Darsu ***@***.***>:
