### ISSUE TITLE
Scopes bugs 

### ISSUE THREAD

**Issue by 1darky** [HaodongMo/ARC-9#19]
- Cheap scopes not work correctly on resolutions lower correctly 1080p
- RT and cheap scopes have different magnification.
- Need something proper for for magnification number, not weird rtfov (idk what to set it to - 3*fov doesn't look like 3x, more like 1x)
- Lasers beam not work in optic

**Comment by HaodongMo** [comment]
Laser won't be fixed, the beam lags in scopes and looks bad. It won't be changed

**Comment by HaodongMo** [comment]
Scope magnification won't be changed

**Comment by HaodongMo** [comment]
cheapscopes/RT differences and resolution issue should be fixed
