### ISSUE TITLE
ARC EFT AK platform GP-25 animations bug

### ISSUE THREAD

**Issue by Tachunkus** [HaodongMo/ARC-9#200]
when you equip gp-34, ready to shoot it and then switch gp-34 to gp-25, gp-25's animation nullify

**Comment by grande1900** [comment]
Not an issue with ARC9 base. Move to [dar-su/arc9_eft_ak](https://github.com/dar-su/arc9_eft_ak)

**Comment by CurlySparkle** [comment]
What grande has said, report the issue to that git instead.
