### ISSUE TITLE
only vertical spread when firing up or down 

### ISSUE THREAD

**Issue by tasteslikefunk** [HaodongMo/ARC-9#203]
doesn't matter what distance, nor any other variables, it just only does vertical spread, not hor and ver.

**Comment by dar-su** [comment]
Can you send video

**Comment by tasteslikefunk** [comment]
https://github.com/HaodongMo/ARC-9/assets/107817867/e167edca-88ad-4ac8-9622-732e636c1fbb

it seems to effect shotguns the most, but still vertical for alot of guns that don't have physical recoil like eft has

**Comment by tasteslikefunk** [comment]
you should try using a random vector cone instead of angle variation to fix it, and try using view punches for the recoil.

**Comment by dar-su** [comment]
Viewpunch is server only, as i know recoil already using some custom client implementation of it

Random vector cone would result into square spread instead of circle

**Comment by tasteslikefunk** [comment]
> Viewpunch is server only, as i know recoil already using some custom client implementation of it
> 
> Random vector cone would result into square spread instead of circle

generate random sin and cosine on vertical and horizontal axis from the 0 point (crosshair center)
it will give you a round cone shaped spread

**Comment by dar-su** [comment]
i guess it already does that? idk
do a pull request if you know how to fix it without breaking stuff (physical and non physical bullets)

really a very minor "bug", people usually shoot enemy on eye level
