### ISSUE TITLE
arc9 causes lua errors when loading a map on x64 temp build

### ISSUE THREAD

**Issue by BadaBingBR** [HaodongMo/ARC-9#205]
[ARC9 Weapon Base] lua/arc9/server/sv_net.lua:1: attempt to call field 'AddNetworkString' (a nil value)
  1. unknown - lua/arc9/server/sv_net.lua:1
   2. include - [C]:-1
    3. unknown - lua/autorun/sh_arc9_autorun.lua:28

[ARC9 Weapon Base] lua/arc9/server/sv_blacklist.lua:61: attempt to index local 'ply' (a nil value)
  1. func - lua/arc9/server/sv_blacklist.lua:61
   2. unknown - lua/includes/extensions/net.lua:33

this happens when loading a map

**Comment by dar-su** [comment]
Use old x64 for now, they changed something related to file.Find in new gmod build
