### ISSUE TITLE
Flickering weapons when using -tickrate 33 in multiplayer

### ISSUE THREAD

**Issue by thejaviertc** [HaodongMo/ARC-9#214]
I tested it with a clean server, just sandbox, ARC9 Base and Gunsmith Arms: Source. When I use -tickrate 60, it's fixed. Also, only happens with weapons, not with grenades or melee.

I'm asking this because I want to use the weapons in DarkRP, where is usual to lower the tickrate to get more performance.

https://github.com/HaodongMo/ARC-9/assets/45662206/1931a5c0-b352-4501-b130-a8b506a9a897

**Comment by OddInc** [comment]
Having the same problem on a 33 tickrate server also using GSR. However, Black Ops weapons do not seem to have this problem.

**Comment by thejaviertc** [comment]
Is almost fixed with this commit 102f838 made by @dar-su. Now when you get a weapon for the first time, it starts flickering for a random time and then stops for all weapons until you reconnect.

https://github.com/HaodongMo/ARC-9/assets/45662206/f5b1ed77-5fc2-4e18-9c8d-2fddfb2308fb


Also, it seems like the viewmodel of the weapons is laggier than before (using -tickrate 33)

**Comment by OddInc** [comment]
Still having flickering problem with GSR after commit and most recent WS update. Does not stop for me.

**Comment by thejaviertc** [comment]
Any news?

**Comment by OddInc** [comment]
A temporary fix is to set `SWEP.UseVisualRecoil = false` in the lua file of each weapon.

**Comment by B1ack4NG** [comment]
Try goto sh_recoil.lua
changing the values of MAGIC1 and MAGIC2 in multiplayer from 89.5 to the default 210
I tried and worked
https://github.com/HaodongMo/ARC-9/pull/226

**Comment by TheOnly8Z** [comment]
Fixed in cf989a8

**Comment by thejaviertc** [comment]
I have just tested it because the update on Steam Workshop was recently, and for me is working perfectly.

Thanks for fixing it.
