### ISSUE TITLE
Weapon model draw at low tickrate

### ISSUE THREAD

**Issue by estebanlobreau** [HaodongMo/ARC-9#215]
Weapon model draw look glitched with low tickrate (11-13) i tried at 66 look good 

https://github.com/HaodongMo/ARC-9/assets/19195363/6538e52a-1b10-455c-8bb8-64ff55c0fce9

**Comment by dar-su** [comment]
This is not a base for darkrp (more for singleplayer or for gamemodes with <16 players)
Please do not set tickrate to such low values

**Comment by estebanlobreau** [comment]
yes but look cool cant fixed with like some settings ?

**Comment by dar-su** [comment]
no, it is really complicated
