### ISSUE TITLE
Weapon:GetPrimaryAmmoType() return pistol ammo on all weapons in server side

### ISSUE THREAD

**Issue by Speedy-VonGofast** [HaodongMo/ARC-9#234]
Using Weapon:GetPrimaryAmmoType() return 3 (pistol ammo) on every Arc9 weapons from every packs in server side. This is not the intended behavior.

However this function works as intended in client side.

**Comment by dar-su** [comment]
Ammo type is dynamic stat and can be get through Weapon:GetValue("Ammo")

**Comment by TheOnly8Z** [comment]
This is still not intended behavior - `GetPrimaryAmmoType()` should return whatever is set at `SWEP.Primary.Ammo`, and ARC9 should be modifying that value whenever updating stats.

@Speedy-VonGofast Can you verify if `SWEP.Primary.Ammo` is the correct value serverside? (I'm assuming you are in a dedicated server environment, if not, let me know.)

**Comment by Speedy-VonGofast** [comment]
> @Speedy-VonGofast Can you verify if `SWEP.Primary.Ammo` is the correct value serverside? (I'm assuming you are in a dedicated server environment, if not, let me know.)

Yes, the `SWEP.Primary.Ammo` is the correct value serverside.

**Comment by littlebabyman** [comment]
I can actually confirm this happens with other weapon bases too

**Comment by TheOnly8Z** [comment]
Might be a gmod issue then. Closing for now - check SWEP.Primary.Ammo or SWEP:GetValue("Ammo") instead of using the function.
