### ISSUE TITLE
Guns picked up on ground causes Sights to be slanted.

### ISSUE THREAD

**Issue by ZetsuboBilly** [HaodongMo/ARC-9#235]
Guns picked up off the ground or off of NPCs with the commands; arc9_npc_autoreplace 1 and arc9_replace_spawned 1 causes gun sights to be slanted. Here is a video for proof. This is not caused by any other addons this is specifically caused by the base on both the Workshop and Github versions of this addon. It is not pack specific either. 

https://streamable.com/im7vlc

**Comment by dar-su** [comment]
fixed in latest commit
