### ISSUE TITLE
Modifying Weapons without using attachments

### ISSUE THREAD

**Issue by senspooky** [HaodongMo/ARC-9#236]
Hi all,

Was wondering if there is a way to “extend” the functionality of an existing ARC9 SWEP without creating custom attachments for it?

ie. I love dar-su’s EFT packs, but hate EFT recoil, so I was intending to write an addon which modifies their recoil behaviour. 

If this doesn’t already exist in some form, I’m happy to add the functionality to do so.

**Comment by dar-su** [comment]
Just write some kind of post register swep table changer like those stat editors
Replace shitty visualrecoil stats with better recoil (though animations would suck)

**Comment by senspooky** [comment]
Thanks, is there any way to do it for attachments as well? I've spent a bit of time looking but can't find a hook to override attachments
