### ISSUE TITLE
ViewModelFlip attachment bug

### ISSUE THREAD

**Issue by Sazuzaki** [HaodongMo/ARC-9#237]
Attachments seem to break when setting ViewModelFlip to true.

Video: https://youtu.be/X_nlndeJJo8

Hopefully this can be fixed; this weapon base is by far the best on workshop atm. I'm just a fan for those M9K-era models on gamebanana, so it would be nice to be able to use the ones that are animated on the left side.

**Comment by dar-su** [comment]
I don't think arc9 is what you would want for m9k models, they don't even have c_hands

See tacrp pack

**Comment by Sazuzaki** [comment]
I actually rigged this specific model to work with c_hands which looks pretty neat.

But I understand, I'll just try TFA or something.

**Comment by littlebabyman** [comment]
manually flip the model yourself in blender, you're already rerigging them, should work good enough no?

**Comment by Sazuzaki** [comment]
Would be worth a try yeah. I just figured it would be easier if the base had native support for ViewModelFlip, but I totally get it if not. 

Regardless, I didn't mean to get you all worked up if that was the case. I was just reporting an issue that I've seen other people have as well.
