### ISSUE TITLE
Crash Game (and PC)

### ISSUE THREAD

**Issue by rytp-tv** [HaodongMo/ARC-9#240]
In addition to the fact that the GMod crashes when changing the level, it also sometimes crashes and freezes my PC completely when switching to optical sight mode (powerful PC) (usually only with optical ones, as I noticed).

In addition, it has a strange bug with optical sights when drawviewmodel = false (screenshot). (All unnecessary addons except arc9 and mw weapons for arc9 are completely disabled).

![image](https://github.com/HaodongMo/ARC-9/assets/44220764/1746f2e7-2900-48f2-a87a-a37630b41cac)
![image](https://github.com/HaodongMo/ARC-9/assets/44220764/9980c3cc-8b9c-4b00-aa51-2bd203c3c082)

When **drawviewmodel = true** :

![image](https://github.com/HaodongMo/ARC-9/assets/44220764/9dbe723d-e112-46e4-b6ad-864aa0022f8b)

Why not use more safer HUDPaint hooks and others, rather than replacing render materials that are unsafe and heavy for debugging and GMOD Engine?

P.S. It is also very rare that he crashes the game when calling the customization menu. Something in the render is spoiling the GMOD, although all my files are verified.

**Comment by dar-su** [comment]
We do not support pirates

**Comment by Fesiug** [comment]
get the fuck outta here with that old ass pirate copy LOL
