### ISSUE TITLE
Animation Problem

### ISSUE THREAD

**Issue by W5zcKFem** [HaodongMo/ARC-9#241]
The weapon is a bit buggy at the shoulder (it goes a bit inside) and when you run it moves strangely (a shape problem maybe??). Is it possible to fix this?

**Comment by W5zcKFem** [comment]
The gun in the shoulder can also be seen in this image posted on content steam: [https://steamuserimages-a.akamaihd.net/ugc/2270444915145847191/017997AD48E82A5A54C2197F408AA45D6D33E51D/?imw=637&imh=358&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=true](https://steamuserimages-a.akamaihd.net/ugc/2270444915145847191/017997AD48E82A5A54C2197F408AA45D6D33E51D/?imw=637&imh=358&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=true)

**Comment by dar-su** [comment]
do not type here
