### ISSUE TITLE
RT Scopes draw interior of scope model and stop working if scope model is not see-through

### ISSUE THREAD

**Issue by UMP45GFL** [HaodongMo/ARC-9#242]
I looked through the settings but couldn't figure out how to disable drawing the gun model in the scope
 
My main problem being the model for a scope I'm using has an opaque front end and I can't change it

Just need an option to toggle drawing the gun model in front of the RT scope if there isn't one already that I failed to find

**Comment by UMP45GFL** [comment]
did not read changelogs, just like I thought, am stupid.

**Comment by UMP45GFL** [comment]
should have an option to forcefully disable render weapon through scope in weapon/attachments though

**Comment by dar-su** [comment]
Thats fully experimental function not meant to be used by anyone
Also it not draw scope model at all in render scene of rt view, so i have zero idea how managed to see part of scope there lol
