### ISSUE TITLE
Gunshots sound like they are mono, not stereo

### ISSUE THREAD

**Issue by Mayaya500** [HaodongMo/ARC-9#245]
When I use the same exact sound on the TFA base, it sounds very nice, the gunshots sound properly on the left and right channel. But on the ARC9 I noticed that they sound pretty much mono...

**Comment by dar-su** [comment]
try convert sounds to .ogg (instead of .wav i suppose)
arc9 have complicated sound layer system with dedicated channels  which may not work great with all sounds

**Comment by Mayaya500** [comment]
Okay I found how to fix it, I removed the ^ in front of the sound.

**Comment by littlebabyman** [comment]
thats the distance variant stereo effect in soundscripts. only do that if you know what you're doing
