### ISSUE TITLE
OPP2 optic not magnified

### ISSUE THREAD

**Issue by TRUMSUNG10** [HaodongMo/ARC-9#247]
When I put siderail version of OPP2 it doesn't magnified while the rail mount version OPP-2B does.
![OPP2](https://github.com/HaodongMo/ARC-9/assets/155042580/0a7d8240-2733-4347-88e3-e318e27a41c9)
![OPP2-B](https://github.com/HaodongMo/ARC-9/assets/155042580/a977aaeb-d2bd-403c-8e03-05528cbf8949)

**Comment by dar-su** [comment]
not related to arc9, it is polyarms issue
will be fixed anyway

**Comment by TRUMSUNG10** [comment]
thank you and clumsy me for post it on arc9

**Comment by MokaAkashiya85** [comment]
This issue has now been fixed on the PolyArms Git.
