### ISSUE TITLE
ARC9 HL2 Level Transitioning Crashes

### ISSUE THREAD

**Issue by DraganTMCE** [HaodongMo/ARC-9#254]
Normally I can use any ARC9 weapons on HL2 map and transitioning to next map, without any problem
But. As soon gmod releases different version on X64 branch using ARC9 weapon like EFT, Polyarms, Black Ops, ETC
It begins to behave weirdly like, the lua starting to spam a bunch of errors and so on, it only happen when the map 
Begin to transitioning on 2nd map, but on the 3rd map transition the gmod crashed on initializing world.

I don't know why it happens, if you guys found the issue that related on map transitioning issue, please let me know.

**Comment by StanPiPJacobs** [comment]
https://github.com/HaodongMo/ARC-9/issues/209
https://github.com/HaodongMo/ARC-9/issues/229

**Comment by DraganTMCE** [comment]
> #209 #229

I've tried 2 of these and it didn't work, and some of the other problem that I encounter after level transition

[ARC9 Weapon Base] lua/arc9/client/cl_rendertarget.lua:4: attempt to call method 'GetActiveWeapon' (a nil value)
    1. v - lua/arc9/client/cl_rendertarget.lua:4
        2. unknown - lua/includes/modules/hook.lua:96
        
and

![20240722175119_1](https://github.com/user-attachments/assets/ac317987-32c2-4533-ae0e-437e1cff3682)

**Comment by dar-su** [comment]
arc9 doesn't like map transitions at all, very known but probably will never be fixed

also in last comment the player entity wasn't even created for some reason

**Comment by DraganTMCE** [comment]
> arc9 doesn't like map transitions at all, very known but probably will never be fixed
> 
> also in last comment the player entity wasn't even created for some reason

Yeah, it did happen like this all time, before gmod getting constant update on x64 branch, level transitioning on arc9 weapons that I've used few months, it never go black screen and no UI or anything like that.

**Comment by DraganTMCE** [comment]
Update : Now I manageable to fix the issue of the ARC9 map transition + lua error spam
The causes of the mod from this --> **ISAWC: Inventory System and Working Containers**
