### ISSUE TITLE
Weapon different positions ie rest pos , ironsight pos , etc aren't networked properly.

### ISSUE THREAD

**Issue by reskihed0311** [HaodongMo/ARC-9#256]
They only show clientside for your player.

**Comment by dar-su** [comment]
Not a bug, it just utilizes viewmodel position, only local player have viewmodel
Networking that or recalculating it for each player would be too bad

Most weapon packs have SWEP.NoTPIKVMPos enabled to not have mismatch or bad unexpected gun positions in 3rd person

**Comment by reskihed0311** [comment]
guh... that makes sense honestly. was just hoping in the future you could seta custom rest position that is networked maybe ?
