### ISSUE TITLE
Optimise attachments picker

### ISSUE THREAD

**Issue by UltraBlackLinux** [HaodongMo/ARC-9#36]
Hey there,
Currently the attachments picker seems to load all attachments even when only inspecting the list of folders.
To improve performance and make the attachment experience a bit better, they should only be loaded when actually visible and that async to avoid massive lagspikes.

Thanks!

EDIT: Removed stupid

**Comment by 1darky** [comment]
I haven't experience any lag spikes related to attachments  so idk what you mean

**Comment by UltraBlackLinux** [comment]
> I haven't experience any lag spikes related to attachments so idk what you mean

I found that browsing the attachment folders causes lagspikes when scrolling and entering folders requiring me to wait several seconds before I can continue modification process.

I want to look into this, but I can't find the file that renders the customisation gui, can you tell me which one it is?

**Comment by UltraBlackLinux** [comment]
I have to correct myself, the lag only appears when using the back button

**Comment by UltraBlackLinux** [comment]
I've decided to run Fprofiler over it to see what the results are: [Here](https://server.chonkyrabbit.eu/files/_bugreports/_Arc9lag/)

I actually think the scrollbar is the laggyness issue. It pops up in both "Bottlenecks" and "Top 50 most expensive function calls". I don't think I can just remove the scrollbar feature since it's somewhat tightly weaved into other essential components (Why tho? Where modularity at?)

**Comment by UltraBlackLinux** [comment]
Okay. Previously I experienced a weird issue (apparently), where every attachment slot would show every attachment as compatible. I don't know, what I did, but it's working now. maybe the addon was just bad.

The issue above lead to the fact that I always had a scrollbar shown for every attachment (specifically in the top category, so the back button obviously lagged out the ui), so it must have something to do with the scrollbars having awful performance.

**Comment by PalindroneV2** [comment]
Bro you turned on chaos mode. The feature is explicitly stated to be extremely unstable.

**Comment by UltraBlackLinux** [comment]
> Bro you turned on chaos mode. The feature is explicitly stated to be extremely unstable.

Oh you mean total anarchy mode? What does that even do? I was just experimenting with it trying to figure out what it does and apparently left it on
