### ISSUE TITLE
removing all guns from inv spams errors

### ISSUE THREAD

**Issue by UltraBlackLinux** [HaodongMo/ARC-9#37]
Hey there,
I just noticed that the console gets spammed with the following error once the all guns have been removed from a player's inventory and an arc9 gun was the last removed one:
```
[arc9] addons/arc9/lua/weapons/arc9_base/cl_vmposition.lua:107: attempt to call method 'Crouching' (a nil value)
```
Please fix this!
Thanks!

**Comment by UltraBlackLinux** [comment]
Just updated and the error still persists.

**Comment by dar-su** [comment]
Can't replicate, what do you use for "removing all guns from inv"?

**Comment by UltraBlackLinux** [comment]
> Can't replicate, what do you use for "removing all guns from inv"?

https://wiki.facepunch.com/gmod/Player:DropWeapon

**Comment by dar-su** [comment]
Fixed
