### ISSUE TITLE
Ability to rebind keys

### ISSUE THREAD

**Issue by UltraBlackLinux** [HaodongMo/ARC-9#40]
Hey there,
The keys are currently not rebindable.
This should be changed (Why is bash E+Enter? Why is changing the firemode bound to E + Zoom?)
Thanks!

**Comment by UltraBlackLinux** [comment]
I have attempted to create such a system, but for some reason adding that to the very confusing sh_convar.lua created a chain reaction of errors that I can't quite explain or make sense of.
[Here](https://server.chonkyrabbit.eu/lettermbox/gufx/) is what I added

**Comment by UltraBlackLinux** [comment]
A better Idea could be to convert all keybinds to commands, allowing players to customise the binds in a better way. (Like with Arctic's Radial binds)

**Comment by HaodongMo** [comment]
Keys all need to be default gmod commands to preserve prediction, so this cannot be done.
