### ISSUE TITLE
Add settings to override specific wepon behavior

### ISSUE THREAD

**Issue by UltraBlackLinux** [HaodongMo/ARC-9#54]
Hey there,

I find that arc9 and it's content is all over the place. I feel like a lot of features should have global overrides to add support for guns which lack it or don't:
- Barrel heat-up
- Chambering
- Attachment Filtering (e.g. Standard Weapons have awesome attachments which are only compatible with those guns for some reason, but I'm sure that they would work with others as well. Same with bullet types.)
I would be very happy to see this in arc9

Thanks!

**Comment by Fesiug** [comment]
not really possible closest thing is total anarchy mode
