### ISSUE TITLE
Default preset icons     suck

### ISSUE THREAD

**Issue by dar-su** [HaodongMo/ARC-9#61]
![image](https://user-images.githubusercontent.com/95997959/189308145-878917a5-279e-483b-9be4-2b9a606c908f.png)
![image](https://user-images.githubusercontent.com/95997959/189308321-f010efd6-9cba-47fb-b04b-ff7aaaa98781.png)
![image](https://user-images.githubusercontent.com/95997959/189308378-91a32e79-6a88-4c2b-8f9c-f2994c11b525.png)

**Comment by VolatileIvory** [comment]
Sorry if this is a bit off topic, but what weapon pack are the weapons in the image from?

**Comment by dar-su** [comment]
> Sorry if this is a bit off topic, but what weapon pack are the weapons in the image from?

Standard pack, glock is private

**Comment by HaodongMo** [comment]
Unfixable. Add a button for "Default" instead.
