### ISSUE TITLE
Rework toggle on f

### ISSUE THREAD

**Issue by dar-su** [HaodongMo/ARC-9#67]
It is should not refresh every fucking att on gun, instead make pressing f toggle only toggleonf atts (maybe put all them in  a table?)

**Comment by Fesiug** [comment]
not possible, it has to recalculate every buff when atts are changed

**Comment by dar-su** [comment]
Everything      is      possible if you try enough

**Comment by Fesiug** [comment]
anything is possible if you could write it for us🥺🥺🥺🥺🥺

**Comment by HaodongMo** [comment]
Not possible, stats need to be recalculated
