### ISSUE TITLE
Hook_TranslateAnimation doesn't work properly with SWEP.Firemodes

### ISSUE THREAD

**Issue by CurlySparkle** [HaodongMo/ARC-9#74]
Using the Hook_TranslateAnimation ( Also the Silencer option )while its inside the SWEP.Firemodes will not work properly as the parts that that the alt animation that the TranslateAnimation is calling for will move back and forth, the only way to fix this is by switching the weapon off and then switch back to it but the problem will still occur if you switch the firemode back to what it was.

Steps to reproduce
- Equip a weapon that has Hook_TranslateAnimation and its extra on the firemode
- Switch firemode

Example to use with this issue https://github.com/HaodongMo/ARC9_Ultralight (Be sure to equip the M4)

**Comment by dar-su** [comment]
seems to be already fixed
