### ISSUE TITLE
SWEP.Penetration error spam issue

### ISSUE THREAD

**Issue by CurlySparkle** [HaodongMo/ARC-9#76]
Whatever you set up a number on the penetration if you shoot at something that comes to penetrate it, it will throw up a bunch of errors

![penetrationerror](https://user-images.githubusercontent.com/5094277/197093449-83a26e70-d6d1-457f-927f-1f24cb41139c.png)

https://user-images.githubusercontent.com/5094277/197093606-46a2c022-1bb0-4eae-9961-8ff97b21c7c1.mp4

**Comment by dar-su** [comment]
Note to arctic: related to physbullets being out of map bounds
