### ISSUE TITLE
EnterSightsSound/ExitSightsSound Will play simultaneously on reload

### ISSUE THREAD

**Issue by CurlySparkle** [HaodongMo/ARC-9#83]
If a weapons come to have these two sounds, every time you reload, both of these sounds will play, either Enter or Exit will play every time you reload.

Steps to reproduce
> Equip a weapon in which has SWEP.EnterSightsSound/ExitSightsSound
> Reload

**Comment by HaodongMo** [comment]
Seems to have been fixed
