### ISSUE TITLE
Visual recoil acts like ass in mp

### ISSUE THREAD

**Issue by dar-su** [HaodongMo/ARC-9#85]
try eft guns in multiplayer, visual recoil will be slow and wont look good

SP:
https://user-images.githubusercontent.com/95997959/200274619-bbd9567e-2254-4bf6-b8e9-75af2c39cbf6.mp4

MP:
https://user-images.githubusercontent.com/95997959/200274660-32077547-246d-499a-a348-641343b6616d.mp4

**Comment by HaodongMo** [comment]
fixed
