### ISSUE TITLE
customise menu weapons rotation jumpy

### ISSUE THREAD

**Issue by UltraBlackLinux** [HaodongMo/ARC-9#91]
Hey there,
I just noticed that the weapon rotation feature in the customisation menu is broken, see [here](https://user-images.githubusercontent.com/62404294/201467951-4b341d5a-3b15-4aa8-b41a-2c9db4d719ed.mp4)
This happens to work on all weapons.
Can you fix this?
Thanks!

**Comment by HaodongMo** [comment]
fixed
