### ISSUE TITLE
Visual additions

### ISSUE THREAD

**Issue by UltraBlackLinux** [HaodongMo/ARC-9#96]
Hey there,
I just thought that a few visual additions would be really nice!
My ideas:
- World blur when ads
- Smoke Effect when shooting

I might add some more here if this isn't closed when I come up with more.
What do you think?
Thanks!

**Comment by dar-su** [comment]
Ads/scope blur was added week ago, smoke effect is based on which muzzle effect you use

**Comment by UltraBlackLinux** [comment]
That blur must be very weak. I never noticed it
